name: rl-workshop
channels:
  - pytorch
dependencies:
- python=3.10.12
- pytorch=2.2.1
- torchvision=0.17.1
- jupyterlab=1.1
- numpy=1.25.2
- pandas=1.5.3
- matplotlib=3.7.1
- seaborn=0.9.0
- ipywidgets
- nodejs
- tqdm==4.41.1
- pip
- pip:
  - gym==0.23.1
  - Pillow==6.2.2